"""init table

Revision ID: 7bf92558ccca
Revises: 
Create Date: 2023-01-17 11:36:57.545413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf92558ccca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('CustomerPK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('CustomerPK')
    )
    op.create_table('product',
    sa.Column('ProductPK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProductName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ProductPK')
    )
    op.create_table('supplier',
    sa.Column('SupplierPK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SupplierName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('SupplierPK')
    )
    op.create_table('transaksi_penerimaan_barang_header',
    sa.Column('TrxInPK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TrxInNo', sa.String(length=255), nullable=False),
    sa.Column('WhsIdf', sa.Integer(), nullable=False),
    sa.Column('TrxInDate', sa.Date(), nullable=True),
    sa.Column('TrxInSuppIdf', sa.Integer(), nullable=False),
    sa.Column('TrxInNotes', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('TrxInPK')
    )
    op.create_table('transaksi_pengeluaran_barang_header',
    sa.Column('TrxOutPK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TrxOutNo', sa.String(length=255), nullable=False),
    sa.Column('WhsIdf', sa.Integer(), nullable=False),
    sa.Column('TrxOutDate', sa.Date(), nullable=True),
    sa.Column('TrxOutSuppIdf', sa.Integer(), nullable=False),
    sa.Column('TrxOutNotes', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('TrxOutPK')
    )
    op.create_table('warehouse',
    sa.Column('WhsPK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('WhsName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('WhsPK')
    )
    op.create_table('transaksi_pengeluaran_barang_detail',
    sa.Column('TrxOutDPK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TrxOutIDF', sa.Integer(), nullable=True),
    sa.Column('TrxOutDProductIdf', sa.Integer(), nullable=False),
    sa.Column('TrxOutDQtyDus', sa.Integer(), nullable=True),
    sa.Column('TrxOutDQtyPcs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['TrxOutIDF'], ['transaksi_pengeluaran_barang_header.TrxOutPK'], ),
    sa.PrimaryKeyConstraint('TrxOutDPK')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi_pengeluaran_barang_detail')
    op.drop_table('warehouse')
    op.drop_table('transaksi_pengeluaran_barang_header')
    op.drop_table('transaksi_penerimaan_barang_header')
    op.drop_table('supplier')
    op.drop_table('product')
    op.drop_table('customer')
    # ### end Alembic commands ###
